import { db, imageGenerations, users } from '@ai-chat/database';
import { sql, eq, and, gte } from 'drizzle-orm';

/**
 * Rate limits for image generation by subscription tier
 */
const IMAGE_LIMITS = {
  free: 10,
  premium: 30,
} as const;

/**
 * Get the number of images generated by a user today
 * @param userId - The user's ID
 * @returns The count of images generated today
 */
export async function getUsageToday(userId: string): Promise<number> {
  const startOfDay = new Date();
  startOfDay.setHours(0, 0, 0, 0);

  const result = await db
    .select({
      count: sql<number>`count(*)`,
    })
    .from(imageGenerations)
    .where(
      and(
        eq(imageGenerations.userId, userId),
        gte(imageGenerations.createdAt, startOfDay)
      )
    );

  return Number(result[0]?.count || 0);
}

/**
 * Check if a user has reached their daily image generation limit
 * @param userId - The user's ID
 * @throws Error with message 'DAILY_LIMIT_REACHED' if limit is exceeded
 * @throws Error if user is not found
 */
export async function checkImageLimit(userId: string): Promise<void> {
  // Get user's subscription tier
  const [user] = await db
    .select({
      subscriptionTier: users.subscriptionTier,
    })
    .from(users)
    .where(eq(users.id, userId));

  if (!user) {
    throw new Error('User not found');
  }

  // Determine the limit based on subscription tier
  const tier = user.subscriptionTier as keyof typeof IMAGE_LIMITS;
  const limit = IMAGE_LIMITS[tier] || IMAGE_LIMITS.free;

  // Get today's usage
  const usage = await getUsageToday(userId);

  // Check if limit is reached
  if (usage >= limit) {
    throw new Error('DAILY_LIMIT_REACHED');
  }
}
